services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: ${APP_NAME:-app}-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
  # Backend Service
  backend:
    build:
      context: ./backend
      target: ${BUILD_TARGET:-development}
    container_name: ${APP_NAME:-app}-backend
    ports:
      - '${BACKEND_PORT:-5000}:5000'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      target: ${BUILD_TARGET:-development}
    container_name: ${APP_NAME:-app}-frontend
    ports:
      - '${FRONTEND_PORT:-5173}:5173'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo-data:
